<div class="page">
	<h2>Contact</h2>

	<p>Contact me using the form below.</p>

	<form method="post" id="contact-form">
        <h3>Your email</h3>
        <input class="form-control" type="text" name="lname" placeholder="" />

        <h3>Anti-spam - enter the current year</h3>
	<input class="form-control" type="text" name="abc" required="required" />

	<h3>Message</h3>
        <div class="form-group">
                <textarea class="form-control " name="message"><?php if (isset($_POST['message'])) echo(htmlspecialchars($_POST['message'])); ?></textarea><br />
        </div>

        <div class="form-group">
	       <input type="submit" value="Send" />
        </div>
	</form>
</div>