<div class="page">
	<h2><?= $page_title ?></h2>

	<form method="POST">
	    <input type="hidden" name="post_id" value="<?= $post['id'] ?>" />
	    <div>
	    	<table style="width:100%">
	    		<tr>
				    <td><h3>Title</h3></td>
				    <td><input id="editor-post-title" type="text" name="title" value="<?= $post['title'] ?>" placeholder="Example title" /></td>
			  	</tr>
	    	</table>
	    </div>

	    <textarea name="content"><?= $post['content'] ?></textarea><br />

	    <div class="form-group">
        	<input type="submit" value="<?php echo ((strcmp($page_title, 'Add a post') == 0) ? 'Add post' : 'Save changes'); ?>" />
        </div>
	</form>

	<script type="text/javascript" src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
	<script type="text/javascript">
	    tinymce.init({
	    	height: "480",
	        selector: "textarea[name=content]",
	        plugins: [
	            "advlist autolink lists link image charmap print preview anchor",
	            "searchreplace visualblocks code fullscreen",
	            "insertdatetime media table contextmenu paste"
	        ],
	        toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
	        entities: "160,nbsp",
	        entity_encoding: "named",
	        entity_encoding: "raw"
	    });
	</script>
</div>


