<div class="post">

	<h2><?= $post['title'] ?></h2>

	<div class="date">
		Posted <?= $post['date'] ?> by <?= $_post['name'] ?>
			
		<?php 
			if (isset($_SESSION['user']['admin']) && ($_SESSION['user']['admin'] == 1)) {
			   echo "<div style='float: right'><a href='/posts/remove/" . $post['post_id'] . "'>Remove post</a> | <a href='/posts/edit/	" . $post['post_id'] . "'>Edit post</a></div>"; 
			}
		?>
	</div>

	<?= $_post['content'] ?><br />
	<?php
		if (!empty($post['tags'])) {
			$tags = explode(',', $post['tags']);

			echo "<div class='tag'><label>Tags: ";

			foreach($tags as $tag) {
				echo "<a href='/tag/" . $tag . "'>" . $tag . "</a> ";
			}

			echo "</div><label>";
		}
	 ?><br />

</div>