<div class="page">
	<h2>Register</h2>
	<form method="post">
        <h3>Name</h3>
        <input class="form-control" type="text" name="name" />

        <h3>Password</h3>
        <input class="form-control" type="password" name="password" />

        <h3>Password repeat</h3>
        <input class="form-control" type="password" name="password_repeat" />
        
        <h3>Enter the current year (antispam)</h3>
        <input class="form-control" type="text" name="abc" /><br />
        
        <div class="form-group">
        	<input type="submit" value="Register" />
        </div>
</form>
</div>